spring:
  application:
    name: cupongapplication

  config:
    import: optional:classpath:application-secret.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/cupongdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
